name: build and deploy
run-name: running deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
permissions:
    id-token: write
jobs:
    test:
        runs-on: ubuntu-latest
        env:
          FLASK_APP: app.py

        steps:
          - name: Checkout
            uses: actions/checkout@v5
          
          - name: Install requirements
            run: |
              pip install -r requirements.txt
              playwright install --with-deps

          
          - name: Start server
            run: |
              flask run --host=127.0.0.1 --port=5000 &
              npx wait-on http://127.0.0.1:5000 --timeout 30000

          - name: Run tests
            run:  python3 -m pytest -v

    deploy:
       runs-on: ubuntu-latest
       needs: test
       steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
            with:
              role-to-assume: arn:aws:iam::261219435789:role/github-actions-jbr
              aws-region: eu-west-2

          - name: Get Caller Identity
            run: aws sts get-caller-identity
        
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
            
          - name: Build, tag, and push docker image to Amazon ECR
            run: |
               docker build -t duties-app .
               docker tag duties-app:latest 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr/duties-app
               docker push 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr/duties-app
