name: learn-github-actions
run-name: running deployment
on: [push]
permissions:
    id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v5

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
            with:
              role-to-assume: arn:aws:iam::261219435789:role/ECR-Deploy-JBR
              aws-region: eu-west-2
              aws-profile-name: jbr-profile
            
          - name: Get Caller Identity
            run: aws sts get-caller-identity
        
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
            env:
                AWS_PROFILE: jbr-profile
            
          - name: Build, tag, and push docker image to Amazon ECR
            run: |
               docker build -t jbr-flask-app .
               docker tag jbr-flask-app:latest 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr-flask-app:latest
               docker push 261219435789.dkr.ecr.eu-west-2.amazonaws.com/jbr-flask-app:latest
